#!/usr/bin/env bash

# (re-)copies the components to node modules, because our app shell insertion relies on
# importing this component from our node modules in the browser.
# This will allow us to test/demo things locally..
dir="node_modules/code-workshop-kit/dist"

if [[ -e $dir ]]; then
  rm -rf "$dir"
fi

mkdir -p $dir

cp -rf dist/components "$dir"